
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- resources:
  - configmap
  - secret
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibmcpcs.ibm.com
  resources:
  - secretshares
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ibmcpcs.ibm.com
  resources:
  - secretshares/status
  verbs:
  - get
  - patch
  - update
